# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_title', models.CharField(max_length=250)),
                ('preacher', models.CharField(max_length=80)),
                ('audiofile', models.FileField(upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='')),
                ('duration', models.TimeField()),
                ('date_created', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='preaching',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Series'),
        ),
    ]
