# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20170927_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preaching',
            name='date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='date',
        ),
        migrations.AddField(
            model_name='preaching',
            name='date_preached',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='series',
            name='date_month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
