# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_auto_20170927_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preaching',
            name='date_preached',
        ),
        migrations.RemoveField(
            model_name='series',
            name='date_month',
        ),
    ]
