# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20170927_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
